local items_table = {
	                                        "wpn_addon_scope",
						"wpn_addon_scope_4x",
	                                        "wpn_addon_scope_acog",
	                                        "wpn_addon_scope_susat",
	                                        "wpn_addon_silencer",
						"wpn_addon_grenade_launcher",
	                                        "wpn_addon_grenade_launcher_m203",
						"cs_light_outfit",
						"cs_light_extra_outfit",
						"cs_standart_outfit",
						"cs_heavy_outfit",
						"cs_heavy_extra_outfit",
						"novice_outfit",
						"novice_outfit_white",
						"stalker_light_outfit",
						"stalker_outfit",
						"stalker_heavy_outfit",
						"scientific_outfit",
						"exo_outfit",
						"bandit_outfit",
						"bandit_veteran_outfit",
						"bandit_master_outfit",
						"bandit_heavy_outfit",
						"soldier_outfit_green",
						"soldier_outfit_grey",
						"soldier_outfit_brown",
						"specops_outfit",
						"military_outfit",
						"military_extra_outfit",
						"svoboda_light_outfit",
						"svoboda_light2_outfit",
						"svoboda_heavy_outfit",
						"svoboda_heavy_extra_outfit",
						"svoboda_scientific_outfit",
						"svoboda_exo_outfit",
						"dolg_outfit",
						"dolg_scientific_outfit",
						"dolg_heavy_outfit",
						"dolg_heavy_extra_outfit",
						"dolg_heavy_extra2_outfit",
						"dolg_exo_outfit",
						"killer_outfit",
						"killer_outfit_dark",
						"killer_light2_outfit",
						"killer_scientific_outfit",
						"killer_exo_outfit",
						"monolith_light_outfit",
						"monolith_outfit",
						"monolith_scientific_outfit",
						"monolith_heavy_outfit",
						"monolith_exo_outfit",
						"red_ecolog_outfit",
						"green_ecolog_outfit",
						"digger_novice_outfit",
						"wpn_bm16",
						"wpn_bm16_full",
						"wpn_toz34",
						"wpn_toz34_obrez",
						"wpn_wincheaster1300",
						"wpn_spas12",
						"wpn_pm",
						"wpn_pb",
						"wpn_pb_short",
						"wpn_fort",
						"wpn_hpsa",
						"wpn_beretta",
						"wpn_walther",
						"wpn_colt1911",
						"wpn_sig220",
						"wpn_usp",
						"wpn_desert_eagle",
						"wpn_mp5",
						"wpn_ak74u",
						"wpn_ak74",
						"wpn_abakan",
						"wpn_l85",
						"wpn_lr300",
						"wpn_sig550",
						"wpn_sig552",
						"wpn_g36",
						"wpn_fn2000",
						"wpn_groza",
						"wpn_val",
						"wpn_vintorez",
						"wpn_pkm",
						"wpn_svd",
						"wpn_svu",
						"wpn_rg-6",
						"wpn_rpg7",
						"wpn_gauss",
						"wpn_gauss_aes",
						"wpn_binoc",
						"wpn_knife",
                                                "grenade_f1",
						"grenade_rgd5",
						"grenade_gd-05",
						"wpn_ak74_minigame",
						"wpn_ak74u_minigame",
						"wpn_beretta_minigame",
						"wpn_lr300_minigame",
						"wpn_mp5_minigame",
						"wpn_pm_minigame",
						"wpn_sig550_minigame",
						"wpn_val_minigame",
						"nuts",
						"olives",
						"cheese",
						"sardines",
						"bread",
						"kolbasa",
						"conserva",
						"vodka",
						"antirad",
						"medkit",
						"medkit_army",
						"medkit_scientic",
						"energy_drink",
						"bandage",
						"device_pda",
						"device_torch",
						"hand_radio",
						"guitar_a",
						"harmonica_a",
						"explosive_dinamit",
						"mutant_dog_tail",
						"mutant_flesh_eye",
						"mutant_boar_leg",
						"mutant_zombie_hand",
						"mutant_izlom_hand",
						"mutant_snork_leg",
						"mutant_cat_tail",
						"mutant_psevdodog_tail",
						"mutant_poltergeist_hand",
						"mutant_burer_hand",
						"mutant_krovosos_jaw",
						"mutant_chimera_nail",
						"mutant_controller_hand",
						"mutant_pseudogigant_nail",
						"mutant_tushkano_face",
						"af_medusa",
						"af_cristall_flower",
						"af_night_star",
						"af_vyvert",
						"af_gravi",
						"af_gold_fish",
						"af_cristall",
						"af_fireball",
						"af_dummy_glassbeads",
						"af_eye",
						"af_fire",
						"af_blood",
						"af_mincer_meat",
						"af_soul",
						"af_fuzz_kolobok",
						"af_baloon",
						"af_glass",
						"af_electra_sparkler",
						"af_electra_flash",
						"af_electra_moonlight",
						"af_dummy_battery",
						"af_dummy_dummy",
						"af_ice",
						"af_compass",
						"af_dummy_pellicle",
						"detector_simple",
						"detector_advanced",
						"detector_elite",
						"device_pda_fang",
						"esc_trader_habar",
						"device_pda_military",
						"device_pda_old",
						"device_pda_garbage_traitor",
						"device_pda_comendant",
						"device_pda_freedom",
						"device_pda_bloodsucker",
						"device_pda_digger",
						"mar_quest_wpn_pm_1",
						"mar_quest_wpn_ak74u_1",
						"mar_quest_af_cristall_flower_1",
						"mar_quest_scout_pda",
						"mar_quest_novice_outfit_1",
						"mil_quest_af_mincer_meat_1",
						"mil_quest_af_fire_1",
						"mil_device_pda_lost_squard",
						"esc_device_pda_driver",
						"agr_pda_for_secret_trader",
						"agr_quest_af_dummy_battery_1",
						"agr_quest_af_fuzz_kolobok_1",
						"agr_map_animals",
						"agr_mechanic_pda",
						"yan_quest_ammo_sleep",
						"yan_quest_granade",
						"yan_quest_scarlet_flower",
						"red_quest_tank_minigun",
						"red_quest_prototipe_device",
						"red_forest_pda_map",
						"red_forest_pda_map_2",
						"flesh_up_ac_mp5",
						"flesh_up_bd_mp5",
						"flesh_up_a_novice_outfit",
						"flesh_up_ac_wincheaster1300",
						"flesh_up_bd_wincheaster1300",
						"flesh_up_ac_ak74u",
						"flesh_up_fh_scientific_outfit",
						"flesh_up_aceg_scientific_outfit",
						"flesh_up_bdfh_scientific_outfit",
						"flesh_up_ab_svu",
						"flesh_up_cd_svu",
						"flesh_up_abcd_svu",
						"flesh_up_ab_pkm",
						"flesh_up_cd_pkm",
						"flesh_up_abcd_pkm",
						"flesh_up_ac_desert_eagle",
						"flesh_up_bd_desert_eagle",
						"flesh_up_ac_spas12"
					}
local ammo_table = {
						"ammo_minigame",
						"ammo_9x18_fmj",
						"ammo_9x18_pmm",
						"ammo_9x18_pbp",
						"ammo_9x19_pbp",
						"ammo_9x19_fmj",
						"ammo_11.43x23_hydro",
						"ammo_11.43x23_fmj",
						"ammo_12x70_buck",
						"ammo_12x76_dart",
						"ammo_12x76_zhekan",
						"ammo_5.45x39_ap",
						"ammo_5.45x39_fmj",
						"ammo_9x39_sp5",
						"ammo_9x39_ap",
						"ammo_9x39_pab9",
						"ammo_5.56x45_ss190",
						"ammo_5.56x45_ap",
						"ammo_7.62x54_7h14",
						"ammo_7.62x54_7h1",
						"ammo_7.62x54_ap",
						"ammo_7.62x39_fmj",
						"ammo_7.62x39_ap",
						"ammo_7.62x25_fmj",
						"ammo_7.62x25_ap",
						"ammo_10.9x32.5",
						"ammo_5.7x28_fmj",
						"ammo_5.7x28_ap",
						"ammo_og-7b",
						"ammo_vog-25p",
						"ammo_vog-25",
						"ammo_m209",
						"ammo_pkm_100",
						"ammo_223_fmj",
						"ammo_gauss",
						"ammo_gauss_aes"
					}

class "spawn_item" (CUIListItemEx)

function spawn_item:__init() super()
	self:SetWndRect		(Frect():set(0,0,300,22))
	
	local ca = 255
	local cr = 216
	local cg = 186
	local cb = 140
	
	self.text					= CUIStatic	()
	self.text:SetAutoDelete		(true)
	self:AttachChild			(self.text)
	self.text:SetWndRect		(Frect():set(0,0,300,22))
	self.text:SetText			("filename")
	self.text:SetFont			(GetFontLetterica18Russian())
	self.text:SetTextColor		(ca,cr,cg,cb)
end


class "spawn_item_dialog" (CUIScriptWnd)

function spawn_item_dialog:__init() super()
   self:InitControls()
   self:InitCallBacks()
   self:FillList()
end

function spawn_item_dialog:__finalize()
end

function spawn_item_dialog:FillList()
	
	for i = 1, #items_table do
		self:AddItemToList(items_table[i])
	end
	for i = 1, #ammo_table do
		self:AddItemToList(ammo_table[i])
	end
end

function spawn_item_dialog:InitControls()
	local xml				= CScriptXmlInit()
	local ctrl
	xml:ParseFile			("ui_spawn_dlg.xml")

	ctrl					= xml:InitStatic("background",self)
	

	self:SetWndPos			(vector2():set(100,100))
	self:SetWndSize			(vector2():set(ctrl:GetWidth(),ctrl:GetHeight()))
	ctrl:SetWndPos			(vector2():set(0,0))

	self.list = xml:InitList	("list",self)
	self.list:ShowSelectedItem	(true)
	self:Register				(self.list, "list_window")

	self.check					= xml:InitCheck("check_own_to_actor",self)
		
	ctrl						= xml:Init3tButton("btn_create",self)	
	self:Register				(ctrl, "btn_create")

	
	ctrl = xml:Init3tButton		("btn_close",self)	
	self:Register				(ctrl, "btn_close")
end

function spawn_item_dialog:InitCallBacks()
	self:AddCallback("btn_create",		ui_events.BUTTON_CLICKED,             self.OnButton_create_clicked,	self)
	self:AddCallback("btn_close",		ui_events.BUTTON_CLICKED,             self.OnButton_close_clicked,	self)
	self:AddCallback("list_window",		ui_events.WINDOW_LBUTTON_DB_CLICK,	  self.OnButton_create_clicked,	self)
end



function spawn_item_dialog:OnButton_create_clicked()	
	if self.list:GetSize()==0 then 
		return 
	end

	local index = self.list:GetSelectedItem()
	
	if index == -1 then 
		return 
	end

	local item			= self.list:GetItem(index)
	local itmname		= item.text:GetText()
	local id
	if self.check:GetCheck() then
		id = db.actor:id()
	else
		id = -1
	end
	
	alife():create(itmname, db.actor:position(), 0, 0, id)
end

function spawn_item_dialog:OnButton_close_clicked()
	self:GetHolder():start_stop_menu	(self,true)
	_G.si_dlg = nil
end

function spawn_item_dialog:OnKeyboard(dik, keyboard_action)
	local bind = dik_to_bind(dik)
	if bind == key_bindings.kQUIT then
		self:OnButton_close_clicked()
	else
	if dik==28 then
		self:OnButton_create_clicked()
	end
	end
	   
	return true
end

function spawn_item_dialog:AddItemToList(item_name)
	local _itm				= spawn_item()
	_itm.text:SetText		(item_name)
	
	self.list:AddItem		(_itm)
end



function main()
	if _G.si_dlg==nil then
		_G.si_dlg = spawn_item_dialog()
	end
	level.start_stop_menu(_G.si_dlg,true)
end
